spring.application.name=cafe
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=embedded
app.jwt.secret=${JWT_SECRET:}
app.jwt.access-token-validity-seconds=3600
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
