CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL,
    user_status VARCHAR(20) NOT NULL,
    point_balance BIGINT NOT NULL DEFAULT 0,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT chk_users_status CHECK (user_status IN ('ADMIN', 'USER')),
    CONSTRAINT chk_users_point_balance CHECK (point_balance >= 0)
);

CREATE TABLE menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT chk_menus_price CHECK (price >= 1),
    CONSTRAINT chk_menus_status CHECK (status IN ('AVAILABLE', 'SOLD_OUT', 'DISCONTINUED'))
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    menu_name VARCHAR(100) NOT NULL,
    payment_amount BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    paid_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_orders_menu FOREIGN KEY (menu_id) REFERENCES menus (id),
    CONSTRAINT chk_orders_payment_amount CHECK (payment_amount >= 1),
    CONSTRAINT chk_orders_status CHECK (status IN ('PAID'))
);

CREATE TABLE point_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_id BIGINT UNIQUE,
    type VARCHAR(20) NOT NULL,
    amount BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_point_transaction_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_point_transaction_type CHECK (type IN ('CHARGE', 'PAYMENT')),
    CONSTRAINT chk_point_transaction_amount CHECK (amount >= 1),
    CONSTRAINT chk_point_transaction_balance_after CHECK (balance_after >= 0),
    CONSTRAINT chk_point_transaction_order_match CHECK (
        (type = 'PAYMENT' AND order_id IS NOT NULL)
        OR (type = 'CHARGE' AND order_id IS NULL)
    )
);

CREATE TABLE order_event_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    event_type VARCHAR(50) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMP,
    sent_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_order_event_outbox_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT chk_order_event_outbox_type CHECK (event_type IN ('ORDER_PAID')),
    CONSTRAINT chk_order_event_outbox_status CHECK (status IN ('PENDING', 'SENDING', 'SENT', 'FAILED')),
    CONSTRAINT chk_order_event_outbox_retry_count CHECK (retry_count >= 0)
);

CREATE INDEX idx_orders_paid_at_menu ON orders (status, paid_at, menu_id);
CREATE INDEX idx_point_transaction_user_created ON point_transaction (user_id, created_at);
CREATE INDEX idx_outbox_status_retry ON order_event_outbox (status, next_retry_at);
