CREATE TABLE point_charge_payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    payment_id VARCHAR(64) NOT NULL UNIQUE,
    amount BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    portone_transaction_id VARCHAR(100),
    paid_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_point_charge_payment_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_point_charge_payment_amount CHECK (amount >= 1),
    CONSTRAINT chk_point_charge_payment_status CHECK (status IN ('READY', 'PAID')),
    CONSTRAINT chk_point_charge_payment_paid_match CHECK (
        (status = 'READY' AND paid_at IS NULL)
        OR (status = 'PAID' AND paid_at IS NOT NULL)
    )
);

CREATE INDEX idx_point_charge_payment_user_created ON point_charge_payment (user_id, created_at);
